### ISSUE TITLE
Select demonstrations for a new dataset

### ISSUE THREAD

**Issue by RealAntonVoronov** [WANGXinyiLinda/concept-based-demonstration-selection#2]
Hello. I would like to use your method to select the best demonstrations for ICL on TREC dataset. However, as I see it is not included in any task sets for which there are provided checkpoints (Yet your code includes preprocessing of this dataset). What is the proper way to implement your method on a new dataset? Does it necessarily include pretraining prefix model from scratch? If yes, how to select tasks to combine them into task suite?

**Comment by WANGXinyiLinda** [comment]
The data preprocessing scripts are directly adopted from MetaICL, so there are more datasets than I used, but it would be too expensive to evaluate them all. You'll need to fine-tune a prefix model from a pre-trained GPT2 (of any size). I suggest you try to add your dataset to the diverse-all task suite, as it is designed to include diverse tasks (according to my knowledge), so it should fit most tasks. The most principled way would be to include as many tasks as possible in the task suite, which could be too slow when you compute the concept token likelihood. Here are all classification tasks in the code base that you can include:

["superglue-rte", "tweet_eval-sentiment", "discovery", "glue-rte", "superglue-wsc", "glue-mrpc", "tweet_eval-stance_hillary", "tweet_eval-offensive", "emotion", "hatexplain", "glue-cola", "sick", "paws", "ethos-sexual_orientation", "glue-qqp", "tweet_eval-emotion", "sms_spam", "health_fact", "glue-mnli", "imdb", "ethos-disability", "glue-wnli", "scitail", "trec-finegrained", "yahoo_answers_topics", "liar", "glue-sst2", "tweet_eval-stance_abortion", "circa", "tweet_eval-stance_climate", "glue-qnli", "tweet_eval-emoji", "ethos-directed_vs_generalized", "ade_corpus_v2-classification", "hate_speech_offensive", "superglue-wic", "google_wellformed_query", "tweet_eval-irony", "ethos-gender", "onestop_english", "trec", "rotten_tomatoes", "kilt_fever", "tweet_eval-stance_feminist", "ethos-national_origin", "tweet_eval-hate", "ag_news", "amazon_polarity", "hate_speech18", "poem_sentiment", "climate_fever", "medical_questions_pairs", "tweet_eval-stance_atheism", "superglue-cb", "dbpedia_14", "wiki_qa", "emo", "yelp_polarity", "ethos-religion", "financial_phrasebank", "tab_fact", "anli", "ethos-race", "poem_sentiment", "climate_fever", "medical_questions_pairs", "financial_phrasebank"]

**Comment by RealAntonVoronov** [comment]
I see. Thank you very much for a fast and clear response.
