### ISSUE TITLE
FileNotFoundError: Couldn't find file at https://www.dropbox.com/s/1pzkadrvffbqw6o/train.txt?dl=1

### ISSUE THREAD

**Issue by PengfeiHePower** [WANGXinyiLinda/concept-based-demonstration-selection#3]
Thanks for sharing codes. I was reproducing the results, and when I installed the data dependencies and downloaded the data following your instructions, I met a problem. I run 'python run.py' in the directory 'preprocess', and I got error: FileNotFoundError: Couldn't find file at https://www.dropbox.com/s/1pzkadrvffbqw6o/train.txt?dl=1. It seems that there are no files in the dropbox.

**Comment by WANGXinyiLinda** [comment]
Hi, sorry for the late reply. It should be a huggingface hub related problem, as all data are hosted on huggingface. The dataset owner probably recently changed the downloading config. I'd suggest you identify the dataset causing the issue, and check the newest huggingface dataset description of it.
