### ISSUE TITLE
 Clarification Needed Regarding Demonstration Selection in LLaMA 2 7b Model

### ISSUE THREAD

**Issue by WJMacro** [WANGXinyiLinda/concept-based-demonstration-selection#4]
Hi there,

Firstly, I appreciate your effort in sharing the codes. I've been attempting to reproduce the results, but I've encountered a challenge that requires some clarification.

In the paper, it's mentioned that demonstrations are selected based on the probability of using (X,Y) as the input to generate concept tokens. This approach seems reasonable for language models like GPT-2, where word embeddings and LM heads are shared. However, I'm uncertain how this process is adapted for language models that do not share word embeddings and LM heads.

Specifically, in models where we haven't pre-trained the parameters in LM heads to generate concept tokens, how is the selection of demonstrations handled? Since the model hasn't been explicitly trained on this task before, the parameters in the LM heads related to concept token generation are untrained.

I'd appreciate any insights or guidance on how to address this issue.

Thank you in advance for your help!

Best regards,
WJMacro.

**Comment by WANGXinyiLinda** [comment]
Hi,

Sorry for the late reply. I was chasing deadlines and almost forgot to
reply. I handle it by inserting the prompt in between x and y and
predicting both the prompt and y such that both LM head and word embeddings
can see the prompt tokens, and you train the embeddings on both sides
separately.

Best,
Xinyi
