### ISSUE TITLE
Too long execution time

### ISSUE THREAD

**Issue by Celeste1114** [WANGXinyiLinda/concept-based-demonstration-selection#5]
I have run exactly the same train.sh file with tasks in tune. It takes 5 hours to execute 100 training steps for sst2 on single A100. It doesn't look normal. The only warning is "The NVIDIA driver on your system is too old". Have you encountered this long execution time? Thanks for your help.

**Comment by WANGXinyiLinda** [comment]
It shouldn't be normal. I'll check the code and make appropriate updates in these few days. Have you tried updating the Nvidia driver?

**Comment by Celeste1114** [comment]
Thanks! I have fixed the problem. Need to upgrade the pytorch-cuda version. :) The version I use now is 11.8.
